kind: Deployment
apiVersion: apps/v1
metadata:
  name: test
  namespace: online
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      tolerations:
      - key: env
        operator: Equal
        value: online
        effect: NoSchedule
      containers:
        - name: nginx
          image: nginx:1.19
          command: ["nginx"]
          args:
            - -g
            - "daemon off;"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: online
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: test
    targetPort: 80
  selector:
    app: test
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
  namespace: online
  annotations:
    configuration.konghq.com: test-linkerd
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - host: test.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: test-linkerd
route:
  preserve_host: false
upstream:
  host_header: test.online.svc
